# fly.toml app configuration file generated for jhs512-slog on 2024-01-29T23:14:03+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jhs512-slog'
primary_region = 'nrt'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = false
min_machines_running = 0
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 2
memory_mb = 2048
